{% set name = "migra" %}
{% set version = "3.0.1663074851" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/migra-{{ version }}.tar.gz
  sha256: dcb7ea8c9a4bb1e713e73f2edc2ace59ca8407fd222d84cd38d21c9c3d8549ab

build:
  entry_points:
    - migra = migra:do_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - schemainspect >=3.1.1658648837
    - six
    - sqlbag

test:
  imports:
    - migra
  commands:
    - pip check
    - migra --help
  requires:
    - pip

about:
  home: https://github.com/djrobstep/migra
  doc_url: https://databaseci.com/docs/migra
  summary: Like `diff` but for PostgreSQL schemas
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
